sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_TABLESTATS --check-column REF_COUNT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_FOREIGN --check-column TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_COLUMNS --check-column LEN --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_BUFFER_POOL_STATS --check-column UNCOMPRESS_CURRENT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_CMPMEM --check-column relocation_time --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_FOREIGN_COLS --check-column POS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_METRICS --check-column COMMENT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_TABLESPACES --check-column ALLOCATED_SIZE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_FT_INDEX_CACHE --check-column POSITION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_FT_INDEX_TABLE --check-column POSITION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_FT_DEFAULT_STOPWORD --check-column value --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_BUFFER_PAGE --check-column FREE_PAGE_CLOCK --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_CMP_PER_INDEX_RESET --check-column uncompress_time --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_FIELDS --check-column POS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_TABLES --check-column SPACE_TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_INDEXES --check-column MERGE_THRESHOLD --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_TEMP_TABLE_INFO --check-column IS_COMPRESSED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_LOCK_WAITS --check-column blocking_lock_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_BUFFER_PAGE_LRU --check-column FREE_PAGE_CLOCK --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_FT_DELETED --check-column DOC_ID --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_CMPMEM_RESET --check-column relocation_time --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_CMP_PER_INDEX --check-column uncompress_time --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_CMP_RESET --check-column uncompress_time --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_FT_BEING_DELETED --check-column DOC_ID --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_CMP --check-column uncompress_time --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_VIRTUAL --check-column BASE_POS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_FT_CONFIG --check-column VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_SYS_DATAFILES --check-column PATH --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_TRX --check-column trx_autocommit_non_locking --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table INNODB_LOCKS --check-column lock_data --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table VIEWS --check-column COLLATION_CONNECTION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table USER_PRIVILEGES --check-column IS_GRANTABLE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table TRIGGERS --check-column DATABASE_COLLATION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table TABLE_PRIVILEGES --check-column IS_GRANTABLE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table TABLE_CONSTRAINTS --check-column CONSTRAINT_TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table TABLESPACES --check-column TABLESPACE_COMMENT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table TABLES --check-column TABLE_COMMENT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table STATISTICS --check-column INDEX_COMMENT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table SESSION_VARIABLES --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table SESSION_STATUS --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table SCHEMA_PRIVILEGES --check-column IS_GRANTABLE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table SCHEMATA --check-column SQL_PATH --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table ROUTINES --check-column DATABASE_COLLATION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table REFERENTIAL_CONSTRAINTS --check-column REFERENCED_TABLE_NAME --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table PROFILING --check-column SOURCE_LINE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table PROCESSLIST --check-column INFO --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table PLUGINS --check-column LOAD_OPTION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table PARTITIONS --check-column TABLESPACE_NAME --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table PARAMETERS --check-column ROUTINE_TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table OPTIMIZER_TRACE --check-column INSUFFICIENT_PRIVILEGES --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table KEY_COLUMN_USAGE --check-column REFERENCED_COLUMN_NAME --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table GLOBAL_VARIABLES --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table GLOBAL_STATUS --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table FILES --check-column EXTRA --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table EVENTS --check-column DATABASE_COLLATION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table ENGINES --check-column SAVEPOINTS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table COLUMN_PRIVILEGES --check-column IS_GRANTABLE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table COLUMNS --check-column GENERATION_EXPRESSION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table COLLATION_CHARACTER_SET_APPLICABILITY --check-column CHARACTER_SET_NAME --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table COLLATIONS --check-column SORTLEN --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/information_schema --username root --password 1234 --table CHARACTER_SETS --check-column MAXLEN --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table users --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table user_schedules --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table tipouts --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table tax_rates --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table tax_profiles --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table tax_exemptions --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table tables --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table super_groups --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table states --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table split_check_details --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table shifts --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table send_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table roles --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table revenue_centers --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table quick_tip_buttons --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table quick_pay_buttons --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table payment_types --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table orders --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table order_tags --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table order_contents --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table modifiers_used --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table modifiers --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table modifier_categories --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table messages --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table menus --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table menu_items --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table menu_groups --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table menu_categories --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table med_customers --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table med_action_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table meal_periods --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table meal_period_types --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table locations --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table location_terminals --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table lk_waivers --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table kds_bumped_tickets --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table kds_bumped_items --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table ingredients --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table ingredient_usage --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table ingredient_categories --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table happyhours --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table forced_modifiers --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table forced_modifier_lists --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table forced_modifier_groups --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table fiscal_reports --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table emp_classes --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table edit_after_send_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table discount_types --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table discount_groups --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table devices --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table device_messages --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table customer_accounts --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table custom_dictionary --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table config --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table clock_punches --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table chain_replications --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table cc_transactions --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table cc_batches --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table cash_data --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table callback_sessions --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table alternate_payment_totals --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table admin_action_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/cafe_nate --username root --password 1234 --table action_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table zendesk_users --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table wait_list --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table us_zip_codes --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table updatelog --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table tutorials --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table tutorial_categories --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table tunnels --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table tracking --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table tos_agreements --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table tokens --check-column token_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table temp_payments --check-column Reserved20 --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table temp_info --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table tax_rates --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table tax_exemptions --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table tables --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table survey --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table supported_swipers --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table supported_printers --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table stats --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table signups --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table restdata --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table restaurants --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table restaurant_notes --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table restaurant_locations --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table restaurant_chains --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reservations --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table resellers_bckup --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table resellers --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reseller_quotes_lineitems --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reseller_quotes --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reseller_licenses --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reseller_leads --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reseller_history --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reseller_devices --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reseller_custom_purchases --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reseller_connects --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reseller_billing_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reports_v2 --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table reports --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table report_parts --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table report_categories --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table releases --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table regions --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table referrals_sent --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table promo_codes --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table printer_models --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table print_jobs --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table payment_status --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table payment_responses --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table payment_request --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table payment_profile --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table payment_hostlink --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table payment_history --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table password_reset_tokens --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table notifications --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table norway_keys --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table new_version_requests --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table monthly_parts --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table monitor_sync --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table monitor_query --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table monitor_gateway --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table messages --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table menu_usage_data --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table master_currencies --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table login_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table loggedin --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table local_servers --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table lavu_monitor_lizard --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table lavu_gift_status --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table lavu_gift_history --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table lavu_gift_cards --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table language_packs --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table language_dictionary_bk --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table language_dictionary.bak --check-column  --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table language_dictionary --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table jc_link --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table invoices --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table invoice_parts --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table helpText --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table heartbeat --check-column server_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table guest_metrics --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table generic_settings --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table gateway_stats --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table extensions_old --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table extensions --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table extension_groups --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table exchange_rates --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table eventlog --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table error_watch --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table employee_work_tracking --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table employee_holidays --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table employeeTimeOff --check-column ID --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table dd_country_mapping --check-column country --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table dd_3pmt3txn --check-column restaurantid --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table dd_1pmt --check-column amount --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table customers_global --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table customer_location_actual --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table customer_backend_usage --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table customer_accounts --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table custom_survey_results --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table cp_action_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table country_region --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table countries --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table components --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table component_packages --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table component_layouts --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table client_devices --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table chain_reporting_groups --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table cc_types --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table can_postal_codes --check-column post_code --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table billing_zuora_webhooks --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table billing_zuora_integration --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table billing_salesforce_events --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table billing_profiles --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table billing_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table billing_idp_locations --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table billing_1pmt_payments_unordered --check-column amount --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table billing_1pmt_payments --check-column ignorethis --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table billing_1pmt --check-column amount --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table beacon_mappings --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table authorizations --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table authnet_899274_1378029 --check-column SubscriptionID --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table auth_tokens --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table api_access_log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table ap_connects --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table ap_blocks --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table all_locations --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table actions --check-column locationid --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table accounts --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/lavu --username root --password 1234 --table Chats --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/myflaskapp --username root --password 1234 --table users --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table user --check-column User --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table time_zone_transition_type --check-column Transition_type_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table time_zone_transition --check-column Transition_time --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table time_zone_name --check-column Name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table time_zone_leap_second --check-column Transition_time --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table time_zone --check-column Time_zone_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table tables_priv --check-column Table_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table slow_log --check-column thread_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table slave_worker_info --check-column Id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table slave_relay_log_info --check-column Channel_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table slave_master_info --check-column Channel_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table servers --check-column Server_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table server_cost --check-column cost_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table proxies_priv --check-column Proxied_user --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table procs_priv --check-column Routine_type --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table proc --check-column type --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table plugin --check-column name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table ndb_binlog_index --check-column orig_epoch --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table innodb_table_stats --check-column table_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table innodb_index_stats --check-column stat_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table help_topic --check-column help_topic_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table help_relation --check-column help_topic_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table help_keyword --check-column help_keyword_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table help_category --check-column help_category_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table gtid_executed --check-column interval_start --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table general_log --check-column argument --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table func --check-column name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table event --check-column name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table engine_cost --check-column device_type --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table db --check-column User --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/mysql --username root --password 1234 --table columns_priv --check-column Column_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table variables_by_thread --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table users --check-column TOTAL_CONNECTIONS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table user_variables_by_thread --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table threads --check-column THREAD_OS_ID --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table table_lock_waits_summary_by_table --check-column MAX_TIMER_WRITE_EXTERNAL --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table table_io_waits_summary_by_table --check-column MAX_TIMER_DELETE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table table_io_waits_summary_by_index_usage --check-column MAX_TIMER_DELETE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table table_handles --check-column EXTERNAL_LOCK --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table status_by_user --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table status_by_thread --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table status_by_host --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table status_by_account --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table socket_summary_by_instance --check-column MAX_TIMER_MISC --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table socket_summary_by_event_name --check-column MAX_TIMER_MISC --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table socket_instances --check-column STATE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table setup_timers --check-column TIMER_NAME --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table setup_objects --check-column TIMED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table setup_instruments --check-column TIMED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table setup_consumers --check-column ENABLED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table setup_actors --check-column HISTORY --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table session_variables --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table session_status --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table session_connect_attrs --check-column ORDINAL_POSITION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table session_account_connect_attrs --check-column ORDINAL_POSITION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table rwlock_instances --check-column READ_LOCKED_BY_COUNT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table replication_group_members --check-column MEMBER_STATE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table replication_group_member_stats --check-column LAST_CONFLICT_FREE_TRANSACTION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table replication_connection_status --check-column LAST_ERROR_TIMESTAMP --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table replication_connection_configuration --check-column TLS_VERSION --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table replication_applier_status_by_worker --check-column LAST_ERROR_TIMESTAMP --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table replication_applier_status_by_coordinator --check-column LAST_ERROR_TIMESTAMP --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table replication_applier_status --check-column COUNT_TRANSACTIONS_RETRIES --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table replication_applier_configuration --check-column DESIRED_DELAY --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table prepared_statements_instances --check-column SUM_NO_GOOD_INDEX_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table performance_timers --check-column TIMER_OVERHEAD --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table objects_summary_global_by_type --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table mutex_instances --check-column LOCKED_BY_THREAD_ID --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table metadata_locks --check-column OWNER_EVENT_ID --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table memory_summary_global_by_event_name --check-column HIGH_NUMBER_OF_BYTES_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table memory_summary_by_user_by_event_name --check-column HIGH_NUMBER_OF_BYTES_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table memory_summary_by_thread_by_event_name --check-column HIGH_NUMBER_OF_BYTES_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table memory_summary_by_host_by_event_name --check-column HIGH_NUMBER_OF_BYTES_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table memory_summary_by_account_by_event_name --check-column HIGH_NUMBER_OF_BYTES_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table hosts --check-column TOTAL_CONNECTIONS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table host_cache --check-column LAST_ERROR_SEEN --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table global_variables --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table global_status --check-column VARIABLE_VALUE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table file_summary_by_instance --check-column MAX_TIMER_MISC --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table file_summary_by_event_name --check-column MAX_TIMER_MISC --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table file_instances --check-column OPEN_COUNT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_waits_summary_global_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_waits_summary_by_user_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_waits_summary_by_thread_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_waits_summary_by_instance --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_waits_summary_by_host_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_waits_summary_by_account_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_waits_history_long --check-column FLAGS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_waits_history --check-column FLAGS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_waits_current --check-column FLAGS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_transactions_summary_global_by_event_name --check-column MAX_TIMER_READ_ONLY --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_transactions_summary_by_user_by_event_name --check-column MAX_TIMER_READ_ONLY --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_transactions_summary_by_thread_by_event_name --check-column MAX_TIMER_READ_ONLY --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_transactions_summary_by_host_by_event_name --check-column MAX_TIMER_READ_ONLY --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_transactions_summary_by_account_by_event_name --check-column MAX_TIMER_READ_ONLY --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_transactions_history_long --check-column NESTING_EVENT_TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_transactions_history --check-column NESTING_EVENT_TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_transactions_current --check-column NESTING_EVENT_TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_summary_global_by_event_name --check-column SUM_NO_GOOD_INDEX_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_summary_by_user_by_event_name --check-column SUM_NO_GOOD_INDEX_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_summary_by_thread_by_event_name --check-column SUM_NO_GOOD_INDEX_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_summary_by_program --check-column SUM_NO_GOOD_INDEX_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_summary_by_host_by_event_name --check-column SUM_NO_GOOD_INDEX_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_summary_by_digest --check-column LAST_SEEN --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_summary_by_account_by_event_name --check-column SUM_NO_GOOD_INDEX_USED --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_history_long --check-column NESTING_EVENT_LEVEL --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_history --check-column NESTING_EVENT_LEVEL --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_statements_current --check-column NESTING_EVENT_LEVEL --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_stages_summary_global_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_stages_summary_by_user_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_stages_summary_by_thread_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_stages_summary_by_host_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_stages_summary_by_account_by_event_name --check-column MAX_TIMER_WAIT --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_stages_history_long --check-column NESTING_EVENT_TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_stages_history --check-column NESTING_EVENT_TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table events_stages_current --check-column NESTING_EVENT_TYPE --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table cond_instances --check-column OBJECT_INSTANCE_BEGIN --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/performance_schema --username root --password 1234 --table accounts --check-column TOTAL_CONNECTIONS --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$waits_global_by_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$waits_by_user_by_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$waits_by_host_by_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$wait_classes_global_by_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$wait_classes_global_by_avg_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$user_summary_by_statement_type --check-column full_scans --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$user_summary_by_statement_latency --check-column full_scans --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$user_summary_by_stages --check-column avg_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$user_summary_by_file_io_type --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$user_summary_by_file_io --check-column io_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$user_summary --check-column total_memory_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$statements_with_temp_tables --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$statements_with_sorting --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$statements_with_runtimes_in_95th_percentile --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$statements_with_full_table_scans --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$statements_with_errors_or_warnings --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$statement_analysis --check-column last_seen --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$session --check-column program_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$schema_tables_with_full_table_scans --check-column latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$schema_table_statistics_with_buffer --check-column innodb_buffer_rows_cached --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$schema_table_statistics --check-column io_misc_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$schema_table_lock_waits --check-column sql_kill_blocking_connection --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$schema_index_statistics --check-column delete_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$schema_flattened_keys --check-column index_columns --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$ps_schema_table_statistics_io --check-column sum_timer_misc --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$ps_digest_avg_latency_distribution --check-column avg_us --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$ps_digest_95th_percentile_by_avg_us --check-column percentile --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$processlist --check-column program_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$memory_global_total --check-column total_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$memory_global_by_current_bytes --check-column high_avg_alloc --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$memory_by_user_by_current_bytes --check-column total_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$memory_by_thread_by_current_bytes --check-column total_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$memory_by_host_by_current_bytes --check-column total_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$latest_file_io --check-column requested --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$io_global_by_wait_by_latency --check-column avg_written --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$io_global_by_wait_by_bytes --check-column total_requested --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$io_global_by_file_by_latency --check-column misc_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$io_global_by_file_by_bytes --check-column write_pct --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$io_by_thread_by_latency --check-column processlist_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$innodb_lock_waits --check-column sql_kill_blocking_connection --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$innodb_buffer_stats_by_table --check-column rows_cached --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$innodb_buffer_stats_by_schema --check-column rows_cached --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$host_summary_by_statement_type --check-column full_scans --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$host_summary_by_statement_latency --check-column full_scans --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$host_summary_by_stages --check-column avg_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$host_summary_by_file_io_type --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$host_summary_by_file_io --check-column io_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table x$host_summary --check-column total_memory_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table waits_global_by_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table waits_by_user_by_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table waits_by_host_by_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table wait_classes_global_by_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table wait_classes_global_by_avg_latency --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table version --check-column mysql_version --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table user_summary_by_statement_type --check-column full_scans --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table user_summary_by_statement_latency --check-column full_scans --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table user_summary_by_stages --check-column avg_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table user_summary_by_file_io_type --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table user_summary_by_file_io --check-column io_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table user_summary --check-column total_memory_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table sys_config --check-column variable --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table statements_with_temp_tables --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table statements_with_sorting --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table statements_with_runtimes_in_95th_percentile --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table statements_with_full_table_scans --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table statements_with_errors_or_warnings --check-column digest --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table statement_analysis --check-column last_seen --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table session_ssl_status --check-column ssl_sessions_reused --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table session --check-column program_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table schema_unused_indexes --check-column index_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table schema_tables_with_full_table_scans --check-column latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table schema_table_statistics_with_buffer --check-column innodb_buffer_rows_cached --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table schema_table_statistics --check-column io_misc_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table schema_table_lock_waits --check-column sql_kill_blocking_connection --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table schema_redundant_indexes --check-column sql_drop_index --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table schema_object_overview --check-column count --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table schema_index_statistics --check-column delete_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table schema_auto_increment_columns --check-column auto_increment_ratio --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table ps_check_lost_instrumentation --check-column variable_value --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table processlist --check-column program_name --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table metrics --check-column Enabled --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table memory_global_total --check-column total_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table memory_global_by_current_bytes --check-column high_avg_alloc --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table memory_by_user_by_current_bytes --check-column total_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table memory_by_thread_by_current_bytes --check-column total_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table memory_by_host_by_current_bytes --check-column total_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table latest_file_io --check-column requested --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table io_global_by_wait_by_latency --check-column avg_written --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table io_global_by_wait_by_bytes --check-column total_requested --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table io_global_by_file_by_latency --check-column misc_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table io_global_by_file_by_bytes --check-column write_pct --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table io_by_thread_by_latency --check-column processlist_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table innodb_lock_waits --check-column sql_kill_blocking_connection --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table innodb_buffer_stats_by_table --check-column rows_cached --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table innodb_buffer_stats_by_schema --check-column rows_cached --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table host_summary_by_statement_type --check-column full_scans --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table host_summary_by_statement_latency --check-column full_scans --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table host_summary_by_stages --check-column avg_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table host_summary_by_file_io_type --check-column max_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table host_summary_by_file_io --check-column io_latency --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/sys --username root --password 1234 --table host_summary --check-column total_memory_allocated --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table xcom --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table variable --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table users --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table task_instance --check-column execution_date --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table task_fail --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table suppliers --check-column supplier_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table slot_pool --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table sla_miss --check-column execution_date --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table log --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table known_event_type --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table known_event --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table job --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table import_error --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table dag_stats --check-column state --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table dag_run --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table dag_pickle --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table dag --check-column dag_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table contacts --check-column contact_id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table connection --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table chart --check-column id --incremental append -m 1
sqoop import --connect jdbc:mysql://localhost/test1 --username root --password 1234 --table alembic_version --check-column version_num --incremental append -m 1
